modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Shadow%20Mounts"
logoFile="icon.png"

[[mods]]
modId="shadowmounts"
version="1.1"
displayName="Shadow Mounts"
displayURL="https://serilum.com/mod/shadow-mounts"
authors="Rick South"
description='''SpookyJam 2024: Turn horses into their Shadow Variant via a unique saddle!
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, LyraKeaton, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.shadowmounts]]
    modId="collective"
    mandatory=true
    versionRange="[7.89,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shadowmounts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.3]"
    ordering="NONE"
    side="BOTH"
